---
# Determine a Repo in your Org to provide 'client-side rules' (located under `.github/rules/`)

# With `.`, the App will look for client-side rules in the Repo that triggerred the event 
# This makes it a 'local' client-side rule. 
# If you provide a specific Repo to store your rules, these Rules will apply
# to any Repo that triggered an Event. 
# This is similar to 'server-side rules', where the Rules are stored directly 
# in the App and therefore applies to any incoming Repo event.
# With the exception that the 'server-side rules' cannot be modified by users!

# Options: `Repo name`, `.` or `none` 
rules_repo: none

# This is a "Lazy Refresh". We only check on an incoming event, if the interval expired.
# The reload interval for client-side rules, in minutes.
rules_refreshInterval: 1